name = "event-parser-cf"
main = "src/index.ts"
workers_dev = false
compatibility_date = "2024-10-26"

# KV Store Binding - unified for all sites
[[kv_namespaces]]
binding = "EVENTS_KV"
id = "462fb1ac6a2c4ed5b53fa0006d2d61b9"

# Secrets (Set via CLI):
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put TELEGRAM_CHAT_ID

# Cron Trigger - Daily at 12:00 KST (03:00 UTC)
[triggers]
crons = [ "0 3 * * *"]

[placement]
mode = "smart"