name = "bloodinfo-event-parser-cf"
type = "service"
main = "src/index.ts"
compatibility_date = "2024-10-26"

# KV Store Binding
[[kv_namespaces]]
binding = "EVENTS_KV"
id = "REPLACE_WITH_YOUR_KV_ID"
preview_id = "REPLACE_WITH_YOUR_PREVIEW_KV_ID"

# Environment Variables
[env.production]
vars = { ENVIRONMENT = "production" }

[env.production.vars]
TELEGRAM_BOT_TOKEN = ""  # Set via 'wrangler secret put TELEGRAM_BOT_TOKEN'
TELEGRAM_CHAT_ID = ""    # Set via 'wrangler secret put TELEGRAM_CHAT_ID'

[env.staging]
vars = { ENVIRONMENT = "staging" }

# Cron Trigger - Daily at 00:00 KST (15:00 UTC previous day)
[[triggers.crons]]
cron = "0 15 * * *"

# Build Configuration
[build]
command = "npm run build"
cwd = "./"
main = "src/index.ts"

[build.upload]
format = "modules"
